# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
