# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
